import io
import base64
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib import colors

def generate_pdf_report(analysis_data: dict) -> str:
    """
    Generates a professional PDF report and returns it as a base64 encoded string.
    NO PERMANENT STORAGE.
    """
    buffer = io.BytesIO()
    c = canvas.Canvas(buffer, pagesize=letter)
    width, height = letter

    # Header
    c.setFont("Helvetica-Bold", 24)
    c.drawString(50, height - 50, "Inspectra AI")
    c.setFont("Helvetica", 14)
    c.drawString(50, height - 75, "Material Analysis Report")
    
    # Line
    c.setStrokeColor(colors.grey)
    c.line(50, height - 85, width - 50, height - 85)
    
    # Content
    c.setFont("Helvetica", 12)
    y_pos = height - 120
    
    c.drawString(50, y_pos, f"Date: {analysis_data.get('timestamp', 'N/A')}")
    y_pos -= 30
    
    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, y_pos, "Analysis Results:")
    y_pos -= 20
    
    c.setFont("Helvetica", 12)
    c.drawString(70, y_pos, f"Similarity Score: {analysis_data.get('similarity_score', 'N/A')}%")
    y_pos -= 20
    c.drawString(70, y_pos, f"Quality Score: {analysis_data.get('quality_score', 'N/A')}/100")
    y_pos -= 20
    c.drawString(70, y_pos, f"Quality Status: {analysis_data.get('quality_status', 'N/A')}")
    y_pos -= 20
    
    c.drawString(70, y_pos, f"Texture Analysis: {analysis_data.get('texture_analysis', 'N/A')}")
    y_pos -= 20
    c.drawString(70, y_pos, f"Pattern Analysis: {analysis_data.get('pattern_analysis', 'N/A')}")
    y_pos -= 30
    
    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, y_pos, "Reference Insights:")
    y_pos -= 20
    c.setFont("Helvetica", 12)
    c.drawString(70, y_pos, analysis_data.get('reference_insights', 'N/A'))
    y_pos -= 30
    
    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, y_pos, "Recommendation:")
    y_pos -= 20
    c.setFont("Helvetica", 12)
    c.drawString(70, y_pos, analysis_data.get('recommendation', 'N/A'))
    
    # Footer
    c.setFont("Helvetica-Oblique", 10)
    c.drawString(50, 50, "Generated by Inspectra AI - Automated Material Intelligence")
    
    c.save()
    buffer.seek(0)
    
    pdf_b64 = base64.b64encode(buffer.read()).decode('utf-8')
    buffer.close()
    
    return pdf_b64
